version: 2.1
jobs:
  mirror-github:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          pwd
          ls -lia

workflows:
  version: 2
  mirror-repositories:
    jobs:
      - mirror-github

