version: 2.1
jobs:
  mirror-github:
    docker:
      - image: cimg/base:stable
    steps:
      - run: . ~/project/.circleci/git-mirror.sh
      
workflows:
  version: 2
  mirror-repositories:
    jobs:
      - mirror-github
      
