version: 2.1
jobs:
  mirror-github:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Mirror repository
          command: |
            WORKDIR="$(mktemp -d)"
            cd "${WORKDIR}"
            pwd
            ls -lia

workflows:
  version: 2
  mirror-repositories:
    jobs:
      - mirror-github

